scverse/napari-spatialdata

examples/raster_regions.py, examples/shape_regions.py
Remaining:
- need clarification on 'layers within view widgets'
- add scalebar for all layers, if current implementation does not include it
=> add scalebar

README.md
Fixing text and links in the Readme.md file
=> Update landing page

src/napari_spatialdata/_interactive.py, tests/test_interactive.py, tests/test_spatialdata.py
in this pr tests are added for the new classes regarding spatialdata and for the changes in previous functionalities
=> testing the interactive class

examples/spatialdata_visium.py, src/napari_spatialdata/_interactive.py, src/napari_spatialdata/_utils.py
This PR adds supports for shapes (circles and polygons) in napari-spatialdata.
=> Add support for circle and polygons (shapes)

src/napari_spatialdata/_interactive.py, src/napari_spatialdata/_model.py, src/napari_spatialdata/_scatterwidgets.py, src/napari_spatialdata/_view.py, src/napari_spatialdata/_widgets.py, tests/test_interactive.py, tests/test_spatialdata.py
handle optional anndata dependency
handles #77
=> optional AnnData in metadata

src/napari_spatialdata/_interactive.py, src/napari_spatialdata/_view.py
handle the problem of layer name update when clicking away and back
=> fix issue with name reinitialization

src/napari_spatialdata/_interactive.py, tests/test_interactive.py
This PR adds the opportunity to change the coordinate system through a public API, thereby completing one task in #158.
=> Public API switch coordinate system

CHANGELOG.md, setup.cfg
Some imports were not in the requirements and some required packages were not used. Fixing this.
=> fixed requirements to match what's used

setup.cfg, src/napari_spatialdata/_model.py, src/napari_spatialdata/_view.py, src/napari_spatialdata/_viewer.py, src/napari_spatialdata/utils/_utils.py, tests/test_spatialdata.py, tests/test_widgets.py
Allows the user to switch between tables.
=> Multi table

setup.cfg, src/napari_spatialdata/_model.py, src/napari_spatialdata/_view.py, src/napari_spatialdata/_viewer.py, src/napari_spatialdata/utils/_utils.py, tests/test_spatialdata.py, tests/test_widgets.py
Reverts scverse/napari-spatialdata#196
=> Revert "Multi table"

.readthedocs.yaml, setup.cfg, tox.ini
Useful to test the build before making a release.
=> Enabling tests and docs against pre-released spatialdata

src/napari_spatialdata/_view.py, src/napari_spatialdata/_widgets.py
- fixed bug appearing when circles are displayed with a napari Points layer
- fixes coloring of categoricals
=> fixed bug circles displayed as points, fixed colors

src/napari_spatialdata/_view.py
This simplifies the conditional when looking for a layer that has `_columns_df` in the metadata and also fixes issues when looking for a layer that has sdata but not name in the metadata.
=> simplify conditional

src/napari_spatialdata/_scatterwidgets.py
With #247 a wrong import was introduced. This PR fixes that import
=> fix import

src/napari_spatialdata/_view.py, src/napari_spatialdata/_widgets.py
The feature is already in main but tests do not pass (partially because a new release in `spatialdata` is required. Let's fix this in this PR after a release is available.
=> showing channel names of images in var list widget

src/napari_spatialdata/_reader.py
This PR silence, warning about trying to start a second event loop in reader. 
cc @melonora
=> Silence warning in data reader

src/napari_spatialdata/utils/_utils.py
Small PR to fix a bug noticed in https://github.com/scverse/napari-spatialdata/issues/241 (it doesn't close the issue).
=> fix return type _adjust_channels_order()

src/napari_spatialdata/_view.py, tests/test_view.py
Closes #282 
The bug is now covered by a test.
=> fix #282 (error in channel selection due to #276)

src/napari_spatialdata/_view.py, tests/test_view.py
closes #302 
(no fix in this PR yet, for the moment I just reproduce the bug)
=> test to reproduce #302

README.md
fixing https://github.com/scverse/spatialdata/issues/889
=> fix docs urls
