- examples/spatialdata_interactive.py
- src/napari_spatialdata/__init__.py
Replacing `napari_spatialdata._interactive import Interactive` with `from napari_spatialdata import Interactive`
> Fixing private module imports

- src/napari_spatialdata/_interactive.py
- src/napari_spatialdata/utils/_utils.py
- tests/test_spatialdata.py
- tests/test_utils.py
* Fixes performance issue with multiscale images. Performance tested on the Xenium + Visium dataset (the one where the performance problem got reported)
* closes https://github.com/scverse/napari-spatialdata/issues/126
* closes https://github.com/scverse/napari-spatialdata/issues/125
* Refactor the name and the docstring of `_transform_to_rgb()`, now called `_adjust_channels_order()`, as the name was misleading. The function is not transforming to RGB, but it's swapping the dims and telling if the image is RGB or not. Also the swap of the dims is done all the time a `c` dimension is present and not just when an RGB image is passed, as the old docstring suggested.
> Fixes performance with multiscale, fixes docs

- src/napari_spatialdata/__main__.py
- src/napari_spatialdata/_interactive.py
> Improved ergonomics of `Interactive`

- src/napari_spatialdata/_sdata_widgets.py
- src/napari_spatialdata/_viewer.py
- src/napari_spatialdata/utils/_utils.py
- tests/test_viewer.py
This PR allows for the affine transform associated with the layer(s) to be updated when the coordinate system is changed. It will ignore layers that do not have an `sdata` object associated with them. 
Furthermore, this PR includes a bugfix for the issue of  a `KeyError` being raised when the visibility of the layer is updated and the layer has no `sdata` associated with it.
> Transform layers

- src/napari_spatialdata/_viewer.py
closes #94 
Add global variables to allow users to adjust the `POLYGON_TRESHOLD` and `POINTS_TRESHOLD` when required.
> add_globals

- README.md
the napari conda-forge package no longer installs a Qt backend, so this PR updates the install instructions analogous to https://github.com/napari/napari/pull/6123
> [Maintenance] Update conda-forge install instructions in README.md

- src/napari_spatialdata/_viewer.py
Instantiation of `SpatialData` does not create a table, implying that the table is optional.
A SpatialData object with just (visual) elements but no annotations can still be of interest for viewing in napari-spatialdata, however it tried to load annotations without checking whether a table exists.
> Add safeguard when table is None

- src/napari_spatialdata/_view.py
- src/napari_spatialdata/_viewer.py
- src/napari_spatialdata/utils/_utils.py
- tests/test_viewer.py
closes #164 
This PR fixes the issue reported in #164. The problem was that when filtering the anndata object it would result in an anndata object with potentially 0 rows. This PR checks whether the anndata object to be added to the metadata has 0 rows. If this is the case then the `adata` metadata is set to be `None`. Also if there is no table, adata will be none, but in addition `region_key` will also be `None`.
In addition to the implementation of @aeisenbarth this handles the case when a table is present, but there are no annotations for a given element.
> Plotting annotations fix

- README.md
- setup.cfg
- src/napari_spatialdata/_reader.py
This PR resolves the comment of @psobolewskiPhD in #185. Specifically it removes those parts of the code related to `npe` and adds instructions in the readme to allow users to use `napari-spatialdata` as the default `.zarr` extension reader.
> remove npe related parts

- setup.cfg
- src/napari_spatialdata/_model.py
- src/napari_spatialdata/_view.py
- src/napari_spatialdata/_viewer.py
- src/napari_spatialdata/utils/_utils.py
- tests/test_spatialdata.py
- tests/test_widgets.py
Implements multi_table in napari-spatialdata
> Multi table

- src/napari_spatialdata/_viewer.py
Closes #179.
This PR implements a workaround, which can be removed when https://github.com/napari/napari/issues/6649 is fixed upstream.
> fix wrong point size when affine specified

- src/napari_spatialdata/_model.py
- src/napari_spatialdata/_view.py
- src/napari_spatialdata/_viewer.py
- src/napari_spatialdata/_widgets.py
closes #203
This issue removes the points in `QtAdataViewWidget` and replaces it by a `QLabel` indicating by which column a layer is being colored. Furthermore the construct of `:column_name` is not added anymore to the layer name. As a result the layer name is not changed when running any operation. 
Furthermore, because of this the removal of elements after coloring operations have been performed is fixed. Previously this would return an error due to the layer name having changed.
> add color by in adata view

- src/napari_spatialdata/_view.py
- src/napari_spatialdata/utils/_utils.py
In spatialdata we adjusted the function `join_sdata_spatialelement_table`. The function is now called `join_spatialelement_table` and works both inside and outside the `SpatialData` object. I adjusted the code here to reflect this.
> adjust to join_spatialelement

- src/napari_spatialdata/_viewer.py
This avoids raising an error on key binding collision when napari-spatialdata is opened/closed multiple times (or the keymap has bin registered by another plugin).
Sorry, my previous fix was in the wrong direction and too permissive. There is no way to "register only if not yet in use", but one can only force override any previous shortcut. Without `override=True`, the error is raised.
> Avoid exception when key binding collides with existing

- src/napari_spatialdata/_view.py
- src/napari_spatialdata/_viewer.py
While working on reproducing of performance problem for points and shapes, I found that adjusting contrast limits do not work for data with 3 channels, that are represented as RGB data. 
This PR contains the following changes:
1) change `channel_changed` from local function to class method 
2) generalize `_channel_changed` to accept any dimensional data. 
3) fix `AnnData` initialization for rgb data
> fix: fix adjusting contrast limits for rgb data

- src/napari_spatialdata/_view.py
It looks like I did not focus enough on #276 and accidentally left `displayed` instead `current_point` in the code. 
It works, when I open PR as image on which I worked was loaded as RGB. Now it is loaded as 3 channels and the current code ends with an exception.
> fix: use `current_point` instead of `displayed` to fix contrast calculation

- README.md
- setup.cfg
Since a long time, the PyQt5 wheels have been available on PyPi. This part of instruction is no longer relevant. 
Also specify PyQt5 dependency using `napari[pyqt5]` to enforce version constraints from napari (to not install incompatible version of `PyQt5`)
> docs: Fix installation instruction

- .github/workflows/release.yml
This PR is modernizing release workflow (and allowing for future switch into trusted publishers) to use most recent tools best practices. 
The main missing thing is to cut information from the changelog file and provide it as a body.
> Modernize release workflow use most recent tool

- .github/workflows/release.yml
In #291 I wrongly assume that artifacts will be available in `dist` directory (like it was in the past before I split my deploy pipeline on multiple jobs).  
This PR fix deploy by use output of previous steep documented here https://github.com/hynek/build-and-inspect-python-package?tab=readme-ov-file#outputs
It should work now.
> Fix deploy by read dist path form output of previous steep

- .github/workflows/release.yml
The `pypa/gh-action-pypi-publish@release` action is a docker-based action and is mounting only part of directories of parent machines. Especially, do not mount `/tmp/` directory where `hynek/build-and-inspect-python-package` is storing the output of build. 
This PR copy output of `hynek/build-and-inspect-python-package` to local directory `dist` to use it in next steeps.
> Fix deploy by using local directory

- .github/BENCHMARK_FAIL_TEMPLATE.md
- .github/workflows/benchmarks.yml
In #289 I have missed one constraint's path that lead to failure reported in #296
This PR fixes it and improves the report template. 
Closes #296
> Fix paths in benchmarks

- .github/workflows/test.yml
- pyproject.toml
- setup.cfg
- src/napari_spatialdata/_model.py
- src/napari_spatialdata/_scatterwidgets.py
- src/napari_spatialdata/_sdata_widgets.py
- src/napari_spatialdata/_view.py
- src/napari_spatialdata/_widgets.py
- src/napari_spatialdata/constants/_utils.py
- src/napari_spatialdata/utils/_categoricals_utils.py
- src/napari_spatialdata/utils/_utils.py
- tests/conftest.py
- tests/test_utils.py
While debugging some code against `python` 3.9, I noticed how using `python` 3.9.0 or `3.9.1` systematically leads to these bugs https://github.com/dask/distributed/issues/7956.
Generally one would install a later patch version, but in this PR I add the constraint explicitly in the dependencies. 
Also I did some cleanup:
- black had `target-version = 'py38'`, I changed it to `py39`
- I am testing against 3.11 instead of 3.10. We could also test against 3.10 instead of only the min-max versions, at the cost of more CI time.
> Minimum 3.9.2, testing against 3.11

- src/napari_spatialdata/_widgets.py
- tests/test_view.py
Fix PR:
- fixes a bug when trying to plot categorical annotations, stored in the dataframe
- adds tests for points, both for categorical and continuous annotations stored in the dataframe column
- allows for categorical colors to be stored in the dataframe column <- **new feature**
> bug categorical annotatoins points

- .github/workflows/benchmarks.yml
It is the next place where I miss that need to be updated when migrating from napari repository. 
closes #306
> Fetch information about latest release informtion from proper repository

- CHANGELOG.md
- src/napari_spatialdata/_view.py
- src/napari_spatialdata/_viewer.py
- src/napari_spatialdata/_widgets.py
- src/napari_spatialdata/utils/_utils.py
Fixes two bugs:
- there was a hardcoded `genes_color`, I fixed this
- if an element with a table was added and removed, the `mode.table` was not being reset, leading to inconsistent behavior
CC @melonora
> Fix bug adata in model not being reset

- CHANGELOG.md
- src/napari_spatialdata/_interactive.py
- src/napari_spatialdata/_model.py
- src/napari_spatialdata/_scatterwidgets.py
- src/napari_spatialdata/_view.py
- src/napari_spatialdata/_viewer.py
- src/napari_spatialdata/_widgets.py
- src/napari_spatialdata/utils/_test_utils.py
- src/napari_spatialdata/utils/_utils.py
- tests/conftest.py
- tests/test_widgets.py
The calculation for the radii of transformed circles was wrong. This was manifested for instance when switching between the `global` and `downscaled_hires` coordinate systems in Visium.
> fix radii of transformed circles

- README.md
- docs/index.md
- docs/limitations.md
- src/napari_spatialdata/_model.py
- src/napari_spatialdata/_scatterwidgets.py
- src/napari_spatialdata/_widgets.py
- src/napari_spatialdata/utils/_utils.py
- tests/conftest.py
- tests/test_spatialdata.py
- tests/test_widgets.py
Closes #242 
Fixed:
- bugs with `layer.properties`:
- on mouse hover the layer properties were not shown (this was visible in previous `napari-spatialdata` versions)
- the correct instance property is now shown; properties were shown for the wrong instance, as reported in #242. 
- This is available for all the types of annotations `obs`, `var`, `obsm` and dataframe columns.
- Available for points and labels. Not for shapes, see issue in `napari`: https://github.com/napari/napari/issues/7306
- plotting a continuous variable on a labels caused:
- the background color to be black instead of transparent; now it's transparent
- the first instance (no matter which index, for instance `2`) to be black, instead of being of a different color
- plotting variables on `obsm` was not working
- the …
> Fix instance id shift bug; fix obsm viz; fix background color labels

- src/napari_spatialdata/_widgets.py
When plotting a categorical obs column on labels, for which colors were present in the anndata, an error occurred. This was because the variable `color_dict`, which should be a `dict`, was an array of hex strings instead. 
This part of the code is not covered by tests; we should have tests like in spatialdata-plot, but since we are going to work on visualization interoperability, it makes sense to wait and have a more general way to test the same plots across all the viewers without having to manually duplicate the code and maintain redundant tests. CC @melonora
> fix plot categorical with colors, on labels

- src/napari_spatialdata/_view.py
- src/napari_spatialdata/utils/_utils.py
CI is red because of this: https://github.com/scverse/napari-spatialdata/pull/343.
The PR fixes two exception that originated when an annotating table `adata` was `None`. I discovered this bug with this code snippet: https://github.com/scverse/spatialdata/pull/864.
> Fix exception due to adata being none
